# Generated by Django 5.0.2 on 2024-02-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="year_of_experience",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
