# Generated by Django 5.0.2 on 2024-03-02 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="product",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="active",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="body",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="created_at",
        ),
        migrations.AddField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="catalog.dish",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="text_comment",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
